# Generated by Django 3.2.7 on 2021-09-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='succession',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='succession',
            name='season',
        ),
        migrations.RemoveField(
            model_name='succession_seasons',
            name='episode',
        ),
        migrations.AddField(
            model_name='succession_cast',
            name='cast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_world.succession'),
        ),
        migrations.AddField(
            model_name='succession_season_episodes',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_world.succession_seasons'),
        ),
        migrations.AddField(
            model_name='succession_season_episodes',
            name='partOfSeason',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='succession_seasons',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_world.succession'),
        ),
    ]
