# Generated by Django 3.2.7 on 2021-09-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_world', '0002_auto_20210913_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Succession_Casts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('birthday', models.DateField()),
                ('succession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_world.succession')),
            ],
        ),
        migrations.RenameField(
            model_name='succession_season_episodes',
            old_name='episode',
            new_name='succession_seasons',
        ),
        migrations.RenameField(
            model_name='succession_seasons',
            old_name='season',
            new_name='succession',
        ),
        migrations.DeleteModel(
            name='Succession_Cast',
        ),
    ]
