# Generated by Django 3.2.7 on 2021-09-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_world', '0003_auto_20210916_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='succession_season_episodes',
            name='partOfSeason',
        ),
        migrations.RemoveField(
            model_name='succession_seasons',
            name='seasonNum',
        ),
    ]
