# Generated by Django 3.2.7 on 2021-09-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_world', '0004_auto_20210921_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='succession_season_episodes',
            name='partOfSeason',
            field=models.IntegerField(null=True),
        ),
    ]
