# Generated by Django 3.2.7 on 2021-09-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_world', '0005_succession_season_episodes_partofseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='succession_season_episodes',
            name='episodeNum',
            field=models.IntegerField(null=True),
        ),
    ]
