# Generated by Django 3.2.7 on 2021-09-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_world', '0006_succession_season_episodes_episodenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='succession_casts',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='succession_seasons',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
