# This is a workflow to help to deploy to Heroku with git

name: Build & Push to Heroku

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ django_prod_env ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Deploy django to heroku
        uses: iamabhishekchakraborty/djangoProject@v2 #Uses an action in the root directory
        id: deploy 
        with: 
            heroku_app_name : ${{ secrets.HEROKU_APP_NAME_GIT }}
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_email_address: ${{ secrets.HEROKU_EMAIL_ADDRESS }}
            use_git: true
            force_push: true
          
        #Use the output  from the hello step
      - name: Get the output status
        run: echo "${{ steps.deploy.outputs.status }}"
      - name: Getting the files in directory
        run: pwd
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Deployment Successfull!
